import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconChecklist,
  IconShieldHalf,
  IconBug,
  IconTool,
  IconPalette,
  IconNotification,
  IconBrowserCheck,
  IconArticle,
  IconMotorbike
  
  
} from '@tabler/icons-react';
import {ListTodo, Package, MessagesSquare, Users, ShieldCheck, Lock, UserX, FileX, ServerOff, Construction, UserCog, Wrench, Palette, Bell, Monitor, HelpCircle, } from "lucide-react"

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  checkList: IconChecklist,
  halfShield: IconShieldHalf,
  bug: IconBug,
  tool: IconTool,
  pallete: IconPalette,
  notification: IconNotification,
  browserCheck: IconBrowserCheck,
  listTodo: ListTodo,
  package: Package,
  message: MessagesSquare,
  users: Users,
  checkShield: ShieldCheck,
  lock: Lock,
  userx: UserX,
  filex: FileX,
  serverOff: ServerOff,
  construction: Construction,
  userCong: UserCog,
  wrench: Wrench,
  palette: Palette,
  bell: Bell,
  monitor: Monitor,
  helpCircle: HelpCircle,
  article: IconArticle,
  bike: IconMotorbike
};
